name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shared:
    uses: pantos-io/ci-workflows/.github/workflows/python-ci.yml@v1
    secrets: inherit

  docker-build:
    runs-on: ubuntu-latest
    needs: [shared]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-v1.0-client-cli-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-v1.0-client-cli-

      - name: Build and load
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --platform=linux/amd64 \
            --build-arg environment=testnet \
            --builder ${{ steps.buildx.outputs.name }} \
            --load \
            --tag ghcr.io/pantos-io/client-cli:latest \
            .

      - name: Test image
        run: |
            docker run --rm ghcr.io/pantos-io/client-cli:latest --help

  build-and-run:
    runs-on: ubuntu-latest
    needs: [shared]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        uses: pantos-io/ci-workflows/.github/actions/install-python-deps@v1

      - name: Run program
        run: |
          source .venv/bin/activate
          ./pantos-client.sh --help
